foundry/config/routes.rb
Foundry::Application.routes.draw do
  get "welcome/index"

 
  root 'welcome#index'

  get 'oauth2callback' => 'welcome#index'
  get '/flash_teams/event_library' => 'flash_teams#event_library'
  get '/flash_teams/event_search' => 'flash_teams#event_search'
  post '/flash_teams/rename' => 'flash_teams#rename'
  

  resources :flash_teams do
    member do 
      delete :destroy
      get :get_status
      post :update_status
      post :update_original_status
      post :update_json
      get :get_json
      post :early_completion_email
      post :get_user_name
      post :delayed_task_finished_email
      post :create
      get :settings
      get :duplicate
      post :settings
    end
  end

  get '/flash_teams/:id/:event_id/delay' => 'flash_teams#delay'
  get '/flash_teams/:id_team/:event_id/get_delay' => 'flash_teams#get_delay'

  resources :members do
    member do
      get :invite
      get :reInvite
      get :invited
      get :confirm_email
      post :register
    end
  end
  
  get '/users/logout' => 'users#logout'
  get '/users/login' => 'users#login'
  
  post '/users/post_login' => 'users#post_login'
  post '/users/post_login' => 'users#post_login'
  
  resources :users do
    member do
      post :create
    end
  end
  

end

foundry/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

foundry/app/helpers/welcome_helper.rb
module WelcomeHelper
end

foundry/app/views/welcome/index.html.erb
<!--
<h1>Welcome to Foundry!</h1>
<p><%= link_to "Flash Teams Library", controller: "flash_teams" %></p>
-->

<style>
	body {
		background-color: black;
		padding-top: 100px;
	}
	a:hover {
		text-decoration: none;
	}
	#center {
		width: 200px;
		margin: 0 auto;
		text-align: center;
		background-color: black;
		color: white;
		font-weight: 100;
		font-size: 30px;
		padding: 50px 100px;
		border: 2px solid #FFF;
		letter-spacing: 5px;
	}
	#actions {
		width: 405px;
		margin: 20px auto;
		text-align: center;
	}
	#actions .link {
		color: white;
		padding: 10px 30px;
		border: 2px solid #FFF;
		letter-spacing: 2px;
		font-weight: 300;
	}
	#actions .link:hover {
		background-color: white;
		color: black;
	}
	
	#flash_notice {
		width: 200px;
		margin: 0 auto;
		margin-bottom: 10px;
		text-align: center;
		background-color: grey;
		color: black;
		font-weight: bold;
		font-size: 20px;
		padding: 50px 100px;
		border: 2px solid #FFF;
		
	}
</style>

<!-- Warning for invalid login --> 
<% if flash[:notice] %>
	<div class="flash_notice" id="flash_notice">
		<p><%= flash[:notice] %></p>
	</div>
<% end %>


<div id="center">FOUNDRY</div>



<div id="actions">
	<%= link_to new_user_path do %>
	<div class="link">Register</div>
	<% end %>
	
	<%= link_to users_login_path do %>
	<div class="link">Login</div>
	<% end %>
</div>